- name: Dotfiles
  hosts: localhost
  connection: local
  tasks:
    - name: Include playbook
      ansible.builtin.import_playbook: "playbooks/Darwin.yml"
      # - playbooks/{{ ansible_facts['os_family'] }}.yml
